/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellersIdRouteImport } from './routes/sellers.$id'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'

const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersIdRoute = SellersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SellersRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/sellers': typeof SellersRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/sellers': typeof SellersRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/sellers': typeof SellersRouteWithChildren
  '/customers/$id': typeof CustomersIdRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/sellers/$id': typeof SellersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/invoices'
    | '/sellers'
    | '/customers/$id'
    | '/invoices/$id'
    | '/sellers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/invoices'
    | '/sellers'
    | '/customers/$id'
    | '/invoices/$id'
    | '/sellers/$id'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/invoices'
    | '/sellers'
    | '/customers/$id'
    | '/invoices/$id'
    | '/sellers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  SellersRoute: typeof SellersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$id': {
      id: '/sellers/$id'
      path: '/$id'
      fullPath: '/sellers/$id'
      preLoaderRoute: typeof SellersIdRouteImport
      parentRoute: typeof SellersRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface SellersRouteChildren {
  SellersIdRoute: typeof SellersIdRoute
}

const SellersRouteChildren: SellersRouteChildren = {
  SellersIdRoute: SellersIdRoute,
}

const SellersRouteWithChildren =
  SellersRoute._addFileChildren(SellersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  SellersRoute: SellersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
